project_name: "nextnode-utils"
name: "@nextnode/utils"
description: "A powerful utility toolkit for Nextnode development"
author: "Nextnode Team"
keywords: "nextnode,utils,toolkit,development,automation"
license: "Apache-2.0"
version: "0.1.0"
template_category: "packages"
template_name: "library" 