name: Generate Project

on:
  workflow_dispatch:
    inputs:
      project_config:
        description: 'Project configuration in YAML format'
        required: true
        type: string
        default: |
          name: "my-awesome-project"
          project_name: "my-awesome-project"
          description: "A new awesome project"
          author: "John Doe"
          create_repo: true
          additional_vars:
            version: "1.0.0"
            license: "MIT"
            node_version: "18.x"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Build project generator
        run: cargo build --release
      
      - name: Create config file
        run: |
          echo "${{ github.event.inputs.project_config }}" > config.yaml
      
      - name: Generate project
        env:
          GITHUB_TOKEN: ${{ secrets.GENERATE_GITHUB_TOKEN }}
        run: |
          ./target/release/project-generator-cli --config config.yaml 